FROM maven:3.8.4-openjdk-17
ENV SENHA_POSTGRESQL postgres

WORKDIR /app
WORKDIR /tmp

RUN git clone https://github.com/matheushajer/projeto-fiap-fase-5.git
WORKDIR /tmp/projeto-fiap-fase-5/pedidos

RUN mvn clean package -DskipTests

# Copia o jar para o diretorio /app
RUN cp target/*.jar /app


WORKDIR /app

# Define o comando para iniciar a API
CMD java -jar $(ls | grep .jar)
